### ISSUE TITLE
直接就panic

### ISSUE THREAD

**Issue by ssqf** [caucy/batch_ping#1]
source:, network:ip
ip 192.168.8.110, sended
ip 192.168.8.120, sended
not the process id
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x32a564]

goroutine 156 [running]:
github.com/caucy/batch_ping/ping.(*BatchPinger).ProcessPacket(0x2d08e60, 0x2d557c4, 0x9, 0x200)
	E:/go_proj/src/github.com/caucy/batch_ping/ping/batch_ping.go:261 +0x1e8
github.com/caucy/batch_ping/ping.(*BatchPinger).RecvICMP(0x2d08e60, 0x2fd6b90, 0x2d05c40)
	E:/go_proj/src/github.com/caucy/batch_ping/ping/batch_ping.go:160 +0x190
created by github.com/caucy/batch_ping/ping.(*BatchPinger).Run
	E:/go_proj/src/github.com/caucy/batch_ping/ping/batch_ping.go:126 +0x1a0

**Comment by caucy** [comment]
tks,  batch_ping should drop the icmp pkg of other process id

**Comment by caucy** [comment]
has fixd
